version: '3.7'

services:
  mongo:
    container_name: mongodb
    volumes:
      - data-volume:/data/db
    image: mongo
  app:
    build: .
    container_name: standupstoreparser
    command: susp-run
    depends_on:
      - mongo

volumes:
  data-volume:
